name: 'Issue auto assign & labeler'

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write
jobs:
  auto-assign-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Label by title/body
        uses: github/issue-labeler@v3.4 
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          include-title: 1
          include-body: 0
          enable-versioned-regex: 0

      - name: Auto assign to issue author
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.issue.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [author]
            });
